import Navbar from "@/components/shared/Navbar/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="background-light850_dark100  relative">
      <Navbar />
      <div className="flex">
        leftsidebar
        <section className="max-md:pd-14 flex min-h-screen flex-1 flex-col px-6 pb-6 pt-36 sm:px-14">
          <div className="mx-auto w-full max-w-5xl ">{children}</div>
        </section>
      </div>
    </main>
  );
}
